[package]
name = "schedule-tasks"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.0"
nom_locate = "4.0.0"
nom-supreme = "0.6.0"
clap = "3.1.2"
regex = "1.5.5"
anyhow = "1.0"

[dev-dependencies]
pretty_assertions = "1"
assert_cmd = "2.0"
predicates = "2.1"



