FROM rust:slim-buster AS builder
WORKDIR /zkp_server
COPY . .
RUN apt update && \
    apt install -y protobuf-compiler && \
    cargo build --release --bin zkp_server

FROM debian:bullseye-slim
RUN apt update && apt install -y ca-certificates
WORKDIR /zkp_server
COPY --from=builder /zkp_server/target/release/zkp_server /usr/local/bin/zkp_server
ENTRYPOINT ["/usr/local/bin/zkp_server"]
